package com.payflow.saga.entity;

public enum SagaState {
    STARTED,
    INVENTORY_RESERVATION_PENDING,
    INVENTORY_RESERVED,
    PAYMENT_PENDING,
    PAYMENT_SUCCEEDED,
    COMPENSATING_INVENTORY,
    ORDER_CANCELLATION_PENDING,
    COMPLETED,
    FAILED
}
